### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by Brayzure** [Brayzure/warframe-drop-rates#3]
- [ ] Overall
  - [x] Database
  - [ ] Web
    - [ ] CSS
    - [x] Headers
    - [ ] Partials
      - [ ] Header
      - [ ] Footer
    - [ ] Views
      - [ ] `/missions/{node}`
        - [x] Structure
      - [ ] `/enemies/{name}`
        - [x] Structure
      - [ ] `/relics/{tier}/{name}`
        - [x] Structure
      - [ ] `/search`
        - [x] Structure
  - [ ] API
    - [ ] Overall
    - [x] Ratelimiting
    - [ ] Relics
      - [x] GET `/relics/{tier}/{name}`
      - [x] GET `/relics`
      - [ ] Overall (consistency, etc)
    - [ ] Missions
      - [x] GET `/missions/{node}`
      - [x] GET `/missions`
      - [ ] Overall (consistency, etc)
    - [ ] Enemies
      - [x] GET `/enemies/{name}`
      - [x] GET `/enemies`
      - [ ] Overall (consistency, etc)
